PREFIX purl: <http://purl.org/dc/elements/1.1/>
PREFIX icc: <http://iconclass.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?code ?broader
WHERE {
  ?notation skos:notation ?code .
  ?notation skos:broader ?broaderNotation .
  ?broaderNotation skos:notation ?broader .
}
